### ISSUE TITLE
The layers for the project are missing. I navigated to data source and found the .gdb files, but...

### ISSUE THREAD

**Issue by mbueno0** [PacktPublishing/ArcGIS-Pro-3.x-Cookbook#1]
_Note I'm not a developer, but I have purchased this book._ 

After following the instructions, extracting the .zip file to the C:\ drive, and renaming the directory to ArcGISPro3Cookbook, none of the layers are connected to the .gdb files. 

When I access the layer's properties to remedy the situation by changing the data source, I get the following error message:

**This container is empty.**

I tried this for Chapter 1, Ex. 1, and Chapter 9, Ex. 1.

I came back to edit this issue, and have tried this for several projects in different chapters. I get the same result. I've tried adding the .gdb files from the **Databases** directory and each of the chapter's database files.

**I'm using ArcGIS Pro v 3.2 with a personal use license.**

When I try to look at the database properties in the Catalog Pane in ArcGIS Pro, I get this message:
![Snag_228d10da](https://github.com/PacktPublishing/ArcGIS-Pro-3.x-Cookbook/assets/7790947/e8b7769d-2917-4c84-a1ad-f2b946f5c0b8)

**Comment by mbueno0** [comment]
I've tried this for several of the projects in different chapters. I get the same result. I've looked at the .gdb files from the Databases directory and each of the chapter's database files.

**Comment by seemanjay-packt** [comment]
Hi @mbueno0!

Thank you for bringing this to our attention. There seems to be a problem downloading the datasets from GitHub. While we address this issue, please access the datasets from Google Drive using the following link , this link is also available in the Readme file, we have now highlighted it for easy access.

https://drive.google.com/file/d/1wfEIHiF18uzbBeZ_AxKp8NDS101HB5Q1/view

Apologies for the inconveniences and thank you for your understanding.

**Comment by mbueno0** [comment]
YAY!
Thank you so much!

Sincerely,
     Michael Bueno

**Comment by Rockhound** [comment]
I should have checked the issues... I was struggling to figure out why I could not get this to work.

Thanks so much!

**Comment by mbueno0** [comment]
Yes. Thanks for fixing this so promptly!

Sincerely,
     Michael Bueno
