### ISSUE TITLE
Broken Links 

### ISSUE THREAD

**Issue by Folsomdweller2024** [PacktPublishing/ArcGIS-Pro-3.x-Cookbook#3]
I have downloaded the data, unzipped the data folder, saved it on C Drive, etc. Twice. 
All .aprx files have broken links and I am unable to set Data Source. 
I had high hopes, and I really like the book, but it is such a headache...

Any help would be greatly appreciated. 

Thank you! 

Folsomdweller2024

**Comment by seemanjay-packt** [comment]
Hi @Folsomdweller2024, access the files from Google Drive; it should work as expected.

Google Drive Link: https://drive.google.com/file/d/1wfEIHiF18uzbBeZ_AxKp8NDS101HB5Q1/view
