### ISSUE TITLE
cloning

### ISSUE THREAD

**Issue by stevenp625** [PacktPublishing/ArcGIS-Pro-3.x-Cookbook#4]
I tried downloading the zip file, but am having issues. How does one go about cloning?

**Comment by seemanjay-packt** [comment]
Hi @stevenp625!

You can download the datasets from Google Drive.

Google Drive Link: https://drive.google.com/file/d/1wfEIHiF18uzbBeZ_AxKp8NDS101HB5Q1/view

**Comment by stevenp625** [comment]
Much appreciated!
